"""Update models

Revision ID: 2d5d306b5d92
Revises: 0001
Create Date: 2026-04-09 19:13:03.061212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5d306b5d92'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('quiz_title', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_scores_id'), 'quiz_scores', ['id'], unique=False)
    op.add_column('quizzes', sa.Column('title', sa.String(), nullable=True))
    op.add_column('quizzes', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('quizzes', sa.Column('question', sa.String(), nullable=False))
    op.add_column('quizzes', sa.Column('options', sa.JSON(), nullable=False))
    op.add_column('quizzes', sa.Column('correct_answer', sa.String(), nullable=False))
    op.drop_column('quizzes', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('quizzes', 'correct_answer')
    op.drop_column('quizzes', 'options')
    op.drop_column('quizzes', 'question')
    op.drop_column('quizzes', 'difficulty')
    op.drop_column('quizzes', 'title')
    op.drop_index(op.f('ix_quiz_scores_id'), table_name='quiz_scores')
    op.drop_table('quiz_scores')
    # ### end Alembic commands ###
