"""Sync main branch manual changes: add latex_content and workspace fields

Revision ID: 2f88837e306c
Revises: 7e71270fdf52
Create Date: 2026-04-14 11:57:41.865539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f88837e306c'
down_revision: Union[str, Sequence[str], None] = '7e71270fdf52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dashboard_user_progress_user_id_key'), 'dashboard_user_progress', type_='unique')
    op.drop_index(op.f('ix_dashboard_user_progress_user_id'), table_name='dashboard_user_progress')
    op.create_index(op.f('ix_dashboard_user_progress_user_id'), 'dashboard_user_progress', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_user_progress_user_id'), table_name='dashboard_user_progress')
    op.create_index(op.f('ix_dashboard_user_progress_user_id'), 'dashboard_user_progress', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('dashboard_user_progress_user_id_key'), 'dashboard_user_progress', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
