"""add_target_interview_count

Revision ID: 4376d6afda73
Revises: 95ed011ec154
Create Date: 2026-06-01 13:31:52.597714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4376d6afda73'
down_revision: Union[str, Sequence[str], None] = '95ed011ec154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('target_interview_count', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'target_interview_count')
    # ### end Alembic commands ###
