"""Add parsed_data to CV

Revision ID: 5612dbc43bfe
Revises: c4f7e9a2b1d3
Create Date: 2026-05-02 08:46:26.550083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5612dbc43bfe'
down_revision: Union[str, Sequence[str], None] = 'c4f7e9a2b1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('parsed_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cvs', 'parsed_data')
    # ### end Alembic commands ###
