"""add_simulation_pipeline_fields

Revision ID: 95ed011ec154
Revises: 07bd0d5200d9
Create Date: 2026-06-01 11:24:26.829767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ed011ec154'
down_revision: Union[str, Sequence[str], None] = '07bd0d5200d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('real_interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('real_interview_type', sa.String(), nullable=True),
    sa.Column('company_questions', sa.Text(), nullable=True),
    sa.Column('app_helpful_rating', sa.Integer(), nullable=True),
    sa.Column('preparation_rating', sa.Integer(), nullable=True),
    sa.Column('what_helped_most', sa.Text(), nullable=True),
    sa.Column('what_to_improve', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('interview_result', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_feedbacks_id'), 'interview_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_interview_feedbacks_user_id'), 'interview_feedbacks', ['user_id'], unique=False)
    op.create_index(op.f('ix_interview_feedbacks_workspace_id'), 'interview_feedbacks', ['workspace_id'], unique=False)
    op.add_column('workspaces', sa.Column('simulation_stage', sa.String(), server_default='cv_preparation', nullable=False))
    op.add_column('workspaces', sa.Column('cv_completed', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('workspaces', sa.Column('cover_letter_completed', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'cover_letter_completed')
    op.drop_column('workspaces', 'cv_completed')
    op.drop_column('workspaces', 'simulation_stage')
    op.drop_index(op.f('ix_interview_feedbacks_workspace_id'), table_name='interview_feedbacks')
    op.drop_index(op.f('ix_interview_feedbacks_user_id'), table_name='interview_feedbacks')
    op.drop_index(op.f('ix_interview_feedbacks_id'), table_name='interview_feedbacks')
    op.drop_table('interview_feedbacks')
    # ### end Alembic commands ###
