"""Refactor quiz system: group questions and link scores

Revision ID: d36f2f1d6789
Revises: 2d5d306b5d92
Create Date: 2026-04-13 08:53:47.085553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd36f2f1d6789'
down_revision: Union[str, Sequence[str], None] = '2d5d306b5d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.add_column('quiz_scores', sa.Column('quiz_id', sa.Integer(), nullable=False))
    op.add_column('quiz_scores', sa.Column('attempt_number', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('quiz_scores_workspace_id_fkey'), 'quiz_scores', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_scores', 'quizzes', ['quiz_id'], ['id'])
    op.drop_column('quiz_scores', 'workspace_id')
    op.drop_column('quiz_scores', 'quiz_title')
    op.drop_column('quiz_scores', 'difficulty')
    op.drop_column('quizzes', 'question')
    op.drop_column('quizzes', 'correct_answer')
    op.drop_column('quizzes', 'options')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'professional_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'education',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'profile_image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('workspaces', 'job_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('workspaces', 'emoji',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('workspaces', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('workspaces', 'emoji',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('workspaces', 'job_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'profile_image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'education',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'professional_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('quizzes', sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('quizzes', sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('quizzes', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('quiz_scores', sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('quiz_scores', sa.Column('quiz_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('quiz_scores', sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quiz_scores', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_scores_workspace_id_fkey'), 'quiz_scores', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('quiz_scores', 'attempt_number')
    op.drop_column('quiz_scores', 'quiz_id')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
