"""add base_cv to users

Revision ID: db4f96fe3be4
Revises: c4f7e9a2b1d3
Create Date: 2026-05-02 09:28:22.564246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4f96fe3be4'
down_revision: Union[str, Sequence[str], None] = 'c4f7e9a2b1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('base_cv', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'base_cv')
    # ### end Alembic commands ###
