"""add_recruiter_portal_tables

Revision ID: e3f92d646aae
Revises: 07bd0d5200d9
Create Date: 2026-06-14 12:21:23.753619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f92d646aae'
down_revision: Union[str, Sequence[str], None] = '07bd0d5200d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('job_openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_openings_company_id'), 'job_openings', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_openings_id'), 'job_openings', ['id'], unique=False)
    op.create_index(op.f('ix_job_openings_title'), 'job_openings', ['title'], unique=False)
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiters_company_id'), 'recruiters', ['company_id'], unique=False)
    op.create_index(op.f('ix_recruiters_email'), 'recruiters', ['email'], unique=True)
    op.create_index(op.f('ix_recruiters_id'), 'recruiters', ['id'], unique=False)
    op.create_table('recruiter_refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_refresh_tokens_id'), 'recruiter_refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_refresh_tokens_recruiter_id'), 'recruiter_refresh_tokens', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_recruiter_refresh_tokens_token'), 'recruiter_refresh_tokens', ['token'], unique=True)
    op.create_table('shortlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_opening_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_opening_id'], ['job_openings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_opening_id', 'candidate_id', name='uq_shortlist_job_candidate')
    )
    op.create_index(op.f('ix_shortlists_candidate_id'), 'shortlists', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_shortlists_id'), 'shortlists', ['id'], unique=False)
    op.create_index(op.f('ix_shortlists_job_opening_id'), 'shortlists', ['job_opening_id'], unique=False)
    op.add_column('users', sa.Column('is_searchable', sa.Boolean(), server_default='false', nullable=False))
    # NOTE: Alembic detected removed columns 'base_cv' and 'university' but we
    # intentionally keep them to avoid breaking other code that references them.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_searchable')
    op.drop_index(op.f('ix_shortlists_job_opening_id'), table_name='shortlists')
    op.drop_index(op.f('ix_shortlists_id'), table_name='shortlists')
    op.drop_index(op.f('ix_shortlists_candidate_id'), table_name='shortlists')
    op.drop_table('shortlists')
    op.drop_index(op.f('ix_recruiter_refresh_tokens_token'), table_name='recruiter_refresh_tokens')
    op.drop_index(op.f('ix_recruiter_refresh_tokens_recruiter_id'), table_name='recruiter_refresh_tokens')
    op.drop_index(op.f('ix_recruiter_refresh_tokens_id'), table_name='recruiter_refresh_tokens')
    op.drop_table('recruiter_refresh_tokens')
    op.drop_index(op.f('ix_recruiters_id'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_email'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_company_id'), table_name='recruiters')
    op.drop_table('recruiters')
    op.drop_index(op.f('ix_job_openings_title'), table_name='job_openings')
    op.drop_index(op.f('ix_job_openings_id'), table_name='job_openings')
    op.drop_index(op.f('ix_job_openings_company_id'), table_name='job_openings')
    op.drop_table('job_openings')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
